### ISSUE TITLE
import COSE can not be resolved

### ISSUE THREAD

**Issue by suspirik** [joakimb/OSCoAP#1]
Hi,

I receive the error attached as image. I tried them both on eclipse and intelliJ and receiving the same error. I googled but what I see was code change recommendations for developers.
I use windows so I run the makeCOSElocal.sh file manually and there is a target folder created and I followed the instructions for importing the project. None of suggestions from intelliJ worked, it prompts "No libraries found for COSE.AlgorithmID"

 Can you please give me suggestion? 
Eclipse: https://drive.google.com/file/d/0B09GkOW0ePeaeGZLal9kRnB5dG8/view?usp=sharing
IntelliJ: https://drive.google.com/file/d/0B09GkOW0ePeaeGZLal9kRnB5dG8/view?usp=sharing
Thanks in advance.
BR
- I do not have COSE folder anywhere and I tried to mvn install but received the error below:
  https://drive.google.com/file/d/0B09GkOW0ePeaNzlMWWFHUGFZSzA/view?usp=sharing

**Comment by suspirik** [comment]
I downloaded cose-java content separetely, after that the error solved.

**Comment by joakimb** [comment]
I'm happy it worked out for you.

**Comment by suspirik** [comment]
Thank you! Do you recommend any tool or command to catch oscoap message frame when code is running? I tried with wireshark and coap filter but it did not work.

**Comment by joakimb** [comment]
Wireshark should work for this project,  are you sure you are capturing on the correct interface? The coap/oscoap packets can be filtered using "coap" and DTLS using "dtls". You will not however be able to decrypt the OSCoAP packet payload using wireshark.

**Comment by suspirik** [comment]
As far as I understood that I should be capturing local area connection,is it the correct one? Is there any other tool that I can decrypt the payload as well?

**Comment by joakimb** [comment]
for the test devTest(), you need to capture the loopback interface. If you instantiate a server or client yourself, it depends on your computer setup. 

There is no decryption tool available except for the java class Decryptor in the project

**Comment by suspirik** [comment]
I enabled npcap loopback and also microsoft loopback adapter, but still can not capture coap messages when I run the code. When I run debug I see a VM adress, I tried replace the localhosts as windows loopback ips but it gave error for devTest.; my loopback ips are not 127.0.0.1 and I just read that I can not capture 127.0.0.1 ip on windows machine.

But when I change the localhost with the loopback ips I have, I receive Tid error. And it is still connecting to 127.0.0.1.
Do you have any suggestion?

what I need to know that when I run the devtest, battery (CPU ) usage and message size and memory usage and also  which ecryption you used in the code.  if this informations included the code where I can find them?
